"""empty message

Revision ID: 10308618cd2d
Revises: 2a373088141c
Create Date: 2023-04-17 08:33:29.020690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10308618cd2d'
down_revision = '2a373088141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_association',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag_association')
    # ### end Alembic commands ###
