"""empty message

Revision ID: e53505dc3577
Revises: 40567b6cc742
Create Date: 2023-04-15 15:35:28.843837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53505dc3577'
down_revision = '40567b6cc742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=72),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.String(length=72),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
